### ISSUE TITLE
Only exact number of zero bits is accepted

### ISSUE THREAD

**Issue by 616slayer616** [CouleeApps/git-power#4]
`
Runs:    715684864 Best found: 00000001d6e8e98fb21368b96a075ae30c6c8e39 (31/28 bits) Time: 289.670476 ~2.470686MH/s000000
`

I tried 32 bits first but stopped after it took too long.
Then I tried 28 and it found 31 zero bits rather quickly.
But it did not stop and use that hash and instead continued searching for 28.

I would have been satisfied with 31 of course.

It would be nice if you could at least choose to accept longer hashes.

I think it might even deadlock if it finds more bits than required.
Hence why it hangs for finding small amounts of zero bits (1,2,3 even 10)

**Comment by Lucius-Q-User** [comment]
#3 should fix this

**Comment by CouleeApps** [comment]
Fixed via #3
